language: node_js
node_js: 
  - "stable"

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod

after_success: 
  - firebase deploy --project sam-easton --token $FIREBASE_TOKEN
